source 'https://supermarket.chef.io'

cookbook 'apt'
cookbook 'ark'
cookbook 'bluepill'
cookbook 'build-essential'
cookbook 'java', '<= 1.19.2'
cookbook 'homebrew', '= 2.0.1'
cookbook 'monit'
cookbook 'ohai'
cookbook 'python'
cookbook 'rsyslog'
cookbook 'windows'
cookbook 'yum'
cookbook 'yum-epel'
cookbook 'elasticsearch', '= 0.3.14'
cookbook 'line', '= 0.6.3'
cookbook 'mongodb'
cookbook 'seven_zip'
