source 'https://supermarket.chef.io'


cookbook 'apt',	'>= 2.3.8'
cookbook 'ark'
cookbook 'bluepill','>= 2.3.1'
cookbook 'build-essential','>= 1.4.2'
cookbook 'java', '<= 1.47.0'
cookbook 'monit', '>= 0.6'
cookbook 'ohai','>= 1.1.12'
cookbook 'python','>= 1.4.6'
cookbook 'rsyslog','>= 1.11.0'
cookbook 'windows','>= 1.30.0'
cookbook 'seven_zip', '= 2.0.0'
cookbook 'yum'
cookbook 'yum-epel','>= 0.3.4'
cookbook 'elasticsearch','= 0.3.14'
#cookbook 'homebrew', '<= 1.13.0'
cookbook 'mongodb'
