source 'https://api.berkshelf.com'

cookbook 'apt', '= 3.0.0', git: 'https://github.com/opscode-cookbooks/apt.git', tag: 'v3.0.0'
cookbook 'ark', git: 'https://github.com/burtlo/ark.git', tag: 'v0.9.0'
cookbook 'bluepill', '>= 2.3.1', git: 'https://github.com/opscode-cookbooks/bluepill.git', tag: 'v2.3.1'
cookbook 'build-essential', '>= 1.4.2', git: 'https://github.com/opscode-cookbooks/build-essential.git', tag: 'v1.4.2'
cookbook 'java', '>= 1.19.2', git: 'https://github.com/sous-chefs/java.git', tag: 'v1.21.2'
cookbook 'monit', '>= 0.6', git: 'https://github.com/apsoto/monit.git'
cookbook 'ohai', '= 3.0.1', git: 'https://github.com/opscode-cookbooks/ohai.git', tag: 'v3.0.1'
cookbook 'python', '>= 1.4.6', git: 'https://github.com/poise/python.git', tag: 'v1.4.6'
cookbook 'rsyslog', '>= 1.11.0', git: 'https://github.com/opscode-cookbooks/rsyslog.git', tag: 'v1.11.0'
# cookbook 'windows', '>= 1.30.0', git: 'https://github.com/opscode-cookbooks/windows.git', tag: 'v1.30.2'
# removed windows cookbook as it should no longer be required
cookbook 'yum', git: 'https://github.com/opscode-cookbooks/yum.git', tag: 'v3.1.0'
cookbook 'yum-epel', '>= 0.3.4', git: 'https://github.com/opscode-cookbooks/yum-epel.git', tag: 'v0.3.4'
cookbook 'elasticsearch', '>= 0.3.14', git: 'https://github.com/elasticsearch/cookbook-elasticsearch.git', tag: 'v0.3.14'
cookbook 'mongodb', git: 'https://github.com/edelight/chef-mongodb'
